/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsNotificationsRouteImport } from './routes/docs.notifications'
import { Route as AuthedInboxRouteImport } from './routes/_authed/inbox'
import { Route as AuthedAdminRouteImport } from './routes/_authed/_admin'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthedSettingsLazyRouteImport = createFileRoute('/_authed/settings')()
const AuthedMessagesIdLazyRouteImport = createFileRoute(
  '/_authed/messages/$id',
)()
const AuthedAdminSystemSettingsLazyRouteImport = createFileRoute(
  '/_authed/_admin/system-settings',
)()
const AuthedAdminDashboardLazyRouteImport = createFileRoute(
  '/_authed/_admin/dashboard',
)()
const AuthedAdminUsersIndexLazyRouteImport = createFileRoute(
  '/_authed/_admin/users/',
)()
const AuthedAdminMessagesIndexLazyRouteImport = createFileRoute(
  '/_authed/_admin/messages/',
)()
const AuthedAdminGroupsIndexLazyRouteImport = createFileRoute(
  '/_authed/_admin/groups/',
)()
const AuthedAdminEventsIndexLazyRouteImport = createFileRoute(
  '/_authed/_admin/events/',
)()
const AuthedAdminMessagesNewLazyRouteImport = createFileRoute(
  '/_authed/_admin/messages/new',
)()
const AuthedAdminMessagesDetailLazyRouteImport = createFileRoute(
  '/_authed/_admin/messages/detail',
)()
const AuthedAdminGroupsDetailLazyRouteImport = createFileRoute(
  '/_authed/_admin/groups/detail',
)()
const AuthedAdminEventsDetailLazyRouteImport = createFileRoute(
  '/_authed/_admin/events/detail',
)()

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsLazyRoute = AuthedSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/settings.lazy').then((d) => d.Route),
)
const DocsNotificationsRoute = DocsNotificationsRouteImport.update({
  id: '/docs/notifications',
  path: '/docs/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedInboxRoute = AuthedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() => import('./routes/_authed/inbox.lazy').then((d) => d.Route))
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMessagesIdLazyRoute = AuthedMessagesIdLazyRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/messages.$id.lazy').then((d) => d.Route),
)
const AuthedAdminSystemSettingsLazyRoute =
  AuthedAdminSystemSettingsLazyRouteImport.update({
    id: '/system-settings',
    path: '/system-settings',
    getParentRoute: () => AuthedAdminRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_admin/system-settings.lazy').then((d) => d.Route),
  )
const AuthedAdminDashboardLazyRoute =
  AuthedAdminDashboardLazyRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthedAdminRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_admin/dashboard.lazy').then((d) => d.Route),
  )
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminUsersIndexLazyRoute =
  AuthedAdminUsersIndexLazyRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthedAdminRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_admin/users/index.lazy').then((d) => d.Route),
  )
const AuthedAdminMessagesIndexLazyRoute =
  AuthedAdminMessagesIndexLazyRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthedAdminRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_admin/messages/index.lazy').then((d) => d.Route),
  )
const AuthedAdminGroupsIndexLazyRoute =
  AuthedAdminGroupsIndexLazyRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthedAdminRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_admin/groups/index.lazy').then((d) => d.Route),
  )
const AuthedAdminEventsIndexLazyRoute =
  AuthedAdminEventsIndexLazyRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthedAdminRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_admin/events/index.lazy').then((d) => d.Route),
  )
const AuthedAdminMessagesNewLazyRoute =
  AuthedAdminMessagesNewLazyRouteImport.update({
    id: '/messages/new',
    path: '/messages/new',
    getParentRoute: () => AuthedAdminRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_admin/messages/new.lazy').then((d) => d.Route),
  )
const AuthedAdminMessagesDetailLazyRoute =
  AuthedAdminMessagesDetailLazyRouteImport.update({
    id: '/messages/detail',
    path: '/messages/detail',
    getParentRoute: () => AuthedAdminRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_admin/messages/detail.lazy').then((d) => d.Route),
  )
const AuthedAdminGroupsDetailLazyRoute =
  AuthedAdminGroupsDetailLazyRouteImport.update({
    id: '/groups/detail',
    path: '/groups/detail',
    getParentRoute: () => AuthedAdminRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_admin/groups/detail.lazy').then((d) => d.Route),
  )
const AuthedAdminEventsDetailLazyRoute =
  AuthedAdminEventsDetailLazyRouteImport.update({
    id: '/events/detail',
    path: '/events/detail',
    getParentRoute: () => AuthedAdminRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_admin/events/detail.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/inbox': typeof AuthedInboxRoute
  '/docs/notifications': typeof DocsNotificationsRoute
  '/settings': typeof AuthedSettingsLazyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AuthedAdminDashboardLazyRoute
  '/system-settings': typeof AuthedAdminSystemSettingsLazyRoute
  '/messages/$id': typeof AuthedMessagesIdLazyRoute
  '/events/detail': typeof AuthedAdminEventsDetailLazyRoute
  '/groups/detail': typeof AuthedAdminGroupsDetailLazyRoute
  '/messages/detail': typeof AuthedAdminMessagesDetailLazyRoute
  '/messages/new': typeof AuthedAdminMessagesNewLazyRoute
  '/events/': typeof AuthedAdminEventsIndexLazyRoute
  '/groups/': typeof AuthedAdminGroupsIndexLazyRoute
  '/messages/': typeof AuthedAdminMessagesIndexLazyRoute
  '/users/': typeof AuthedAdminUsersIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/inbox': typeof AuthedInboxRoute
  '/docs/notifications': typeof DocsNotificationsRoute
  '/settings': typeof AuthedSettingsLazyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AuthedAdminDashboardLazyRoute
  '/system-settings': typeof AuthedAdminSystemSettingsLazyRoute
  '/messages/$id': typeof AuthedMessagesIdLazyRoute
  '/events/detail': typeof AuthedAdminEventsDetailLazyRoute
  '/groups/detail': typeof AuthedAdminGroupsDetailLazyRoute
  '/messages/detail': typeof AuthedAdminMessagesDetailLazyRoute
  '/messages/new': typeof AuthedAdminMessagesNewLazyRoute
  '/events': typeof AuthedAdminEventsIndexLazyRoute
  '/groups': typeof AuthedAdminGroupsIndexLazyRoute
  '/messages': typeof AuthedAdminMessagesIndexLazyRoute
  '/users': typeof AuthedAdminUsersIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/_admin': typeof AuthedAdminRouteWithChildren
  '/_authed/inbox': typeof AuthedInboxRoute
  '/docs/notifications': typeof DocsNotificationsRoute
  '/_authed/settings': typeof AuthedSettingsLazyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/_admin/dashboard': typeof AuthedAdminDashboardLazyRoute
  '/_authed/_admin/system-settings': typeof AuthedAdminSystemSettingsLazyRoute
  '/_authed/messages/$id': typeof AuthedMessagesIdLazyRoute
  '/_authed/_admin/events/detail': typeof AuthedAdminEventsDetailLazyRoute
  '/_authed/_admin/groups/detail': typeof AuthedAdminGroupsDetailLazyRoute
  '/_authed/_admin/messages/detail': typeof AuthedAdminMessagesDetailLazyRoute
  '/_authed/_admin/messages/new': typeof AuthedAdminMessagesNewLazyRoute
  '/_authed/_admin/events/': typeof AuthedAdminEventsIndexLazyRoute
  '/_authed/_admin/groups/': typeof AuthedAdminGroupsIndexLazyRoute
  '/_authed/_admin/messages/': typeof AuthedAdminMessagesIndexLazyRoute
  '/_authed/_admin/users/': typeof AuthedAdminUsersIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/inbox'
    | '/docs/notifications'
    | '/settings'
    | '/api/auth/$'
    | '/dashboard'
    | '/system-settings'
    | '/messages/$id'
    | '/events/detail'
    | '/groups/detail'
    | '/messages/detail'
    | '/messages/new'
    | '/events/'
    | '/groups/'
    | '/messages/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/inbox'
    | '/docs/notifications'
    | '/settings'
    | '/api/auth/$'
    | '/dashboard'
    | '/system-settings'
    | '/messages/$id'
    | '/events/detail'
    | '/groups/detail'
    | '/messages/detail'
    | '/messages/new'
    | '/events'
    | '/groups'
    | '/messages'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/_admin'
    | '/_authed/inbox'
    | '/docs/notifications'
    | '/_authed/settings'
    | '/api/auth/$'
    | '/_authed/_admin/dashboard'
    | '/_authed/_admin/system-settings'
    | '/_authed/messages/$id'
    | '/_authed/_admin/events/detail'
    | '/_authed/_admin/groups/detail'
    | '/_authed/_admin/messages/detail'
    | '/_authed/_admin/messages/new'
    | '/_authed/_admin/events/'
    | '/_authed/_admin/groups/'
    | '/_authed/_admin/messages/'
    | '/_authed/_admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DocsNotificationsRoute: typeof DocsNotificationsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsLazyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/docs/notifications': {
      id: '/docs/notifications'
      path: '/docs/notifications'
      fullPath: '/docs/notifications'
      preLoaderRoute: typeof DocsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/inbox': {
      id: '/_authed/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthedInboxRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin': {
      id: '/_authed/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/messages/$id': {
      id: '/_authed/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthedMessagesIdLazyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin/system-settings': {
      id: '/_authed/_admin/system-settings'
      path: '/system-settings'
      fullPath: '/system-settings'
      preLoaderRoute: typeof AuthedAdminSystemSettingsLazyRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/dashboard': {
      id: '/_authed/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedAdminDashboardLazyRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_admin/users/': {
      id: '/_authed/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthedAdminUsersIndexLazyRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/messages/': {
      id: '/_authed/_admin/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthedAdminMessagesIndexLazyRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/groups/': {
      id: '/_authed/_admin/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthedAdminGroupsIndexLazyRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/events/': {
      id: '/_authed/_admin/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthedAdminEventsIndexLazyRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/messages/new': {
      id: '/_authed/_admin/messages/new'
      path: '/messages/new'
      fullPath: '/messages/new'
      preLoaderRoute: typeof AuthedAdminMessagesNewLazyRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/messages/detail': {
      id: '/_authed/_admin/messages/detail'
      path: '/messages/detail'
      fullPath: '/messages/detail'
      preLoaderRoute: typeof AuthedAdminMessagesDetailLazyRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/groups/detail': {
      id: '/_authed/_admin/groups/detail'
      path: '/groups/detail'
      fullPath: '/groups/detail'
      preLoaderRoute: typeof AuthedAdminGroupsDetailLazyRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/events/detail': {
      id: '/_authed/_admin/events/detail'
      path: '/events/detail'
      fullPath: '/events/detail'
      preLoaderRoute: typeof AuthedAdminEventsDetailLazyRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminDashboardLazyRoute: typeof AuthedAdminDashboardLazyRoute
  AuthedAdminSystemSettingsLazyRoute: typeof AuthedAdminSystemSettingsLazyRoute
  AuthedAdminEventsDetailLazyRoute: typeof AuthedAdminEventsDetailLazyRoute
  AuthedAdminGroupsDetailLazyRoute: typeof AuthedAdminGroupsDetailLazyRoute
  AuthedAdminMessagesDetailLazyRoute: typeof AuthedAdminMessagesDetailLazyRoute
  AuthedAdminMessagesNewLazyRoute: typeof AuthedAdminMessagesNewLazyRoute
  AuthedAdminEventsIndexLazyRoute: typeof AuthedAdminEventsIndexLazyRoute
  AuthedAdminGroupsIndexLazyRoute: typeof AuthedAdminGroupsIndexLazyRoute
  AuthedAdminMessagesIndexLazyRoute: typeof AuthedAdminMessagesIndexLazyRoute
  AuthedAdminUsersIndexLazyRoute: typeof AuthedAdminUsersIndexLazyRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminDashboardLazyRoute: AuthedAdminDashboardLazyRoute,
  AuthedAdminSystemSettingsLazyRoute: AuthedAdminSystemSettingsLazyRoute,
  AuthedAdminEventsDetailLazyRoute: AuthedAdminEventsDetailLazyRoute,
  AuthedAdminGroupsDetailLazyRoute: AuthedAdminGroupsDetailLazyRoute,
  AuthedAdminMessagesDetailLazyRoute: AuthedAdminMessagesDetailLazyRoute,
  AuthedAdminMessagesNewLazyRoute: AuthedAdminMessagesNewLazyRoute,
  AuthedAdminEventsIndexLazyRoute: AuthedAdminEventsIndexLazyRoute,
  AuthedAdminGroupsIndexLazyRoute: AuthedAdminGroupsIndexLazyRoute,
  AuthedAdminMessagesIndexLazyRoute: AuthedAdminMessagesIndexLazyRoute,
  AuthedAdminUsersIndexLazyRoute: AuthedAdminUsersIndexLazyRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedInboxRoute: typeof AuthedInboxRoute
  AuthedSettingsLazyRoute: typeof AuthedSettingsLazyRoute
  AuthedMessagesIdLazyRoute: typeof AuthedMessagesIdLazyRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedInboxRoute: AuthedInboxRoute,
  AuthedSettingsLazyRoute: AuthedSettingsLazyRoute,
  AuthedMessagesIdLazyRoute: AuthedMessagesIdLazyRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DocsNotificationsRoute: DocsNotificationsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
