/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as DocsRoleBasedAccessRouteImport } from './routes/docs.role-based-access'
import { Route as DocsNotificationsRouteImport } from './routes/docs.notifications'
import { Route as DocsLicensingRouteImport } from './routes/docs.licensing'
import { Route as DocsGroupManagementRouteImport } from './routes/docs.group-management'
import { Route as DocsEventManagementRouteImport } from './routes/docs.event-management'
import { Route as DocsDeliveryTrackingRouteImport } from './routes/docs.delivery-tracking'
import { Route as DocsBroadcastMessagesRouteImport } from './routes/docs.broadcast-messages'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedInboxRouteImport } from './routes/_authed/inbox'
import { Route as AuthedAdminRouteImport } from './routes/_authed/_admin'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedMessagesIdRouteImport } from './routes/_authed/messages.$id'
import { Route as AuthedAdminSystemSettingsRouteImport } from './routes/_authed/_admin/system-settings'
import { Route as AuthedAdminDashboardRouteImport } from './routes/_authed/_admin/dashboard'
import { Route as AuthedAdminUsersIndexRouteImport } from './routes/_authed/_admin/users/index'
import { Route as AuthedAdminMessagesIndexRouteImport } from './routes/_authed/_admin/messages/index'
import { Route as AuthedAdminGroupsIndexRouteImport } from './routes/_authed/_admin/groups/index'
import { Route as AuthedAdminEventsIndexRouteImport } from './routes/_authed/_admin/events/index'
import { Route as AuthedAdminMessagesNewRouteImport } from './routes/_authed/_admin/messages/new'
import { Route as AuthedAdminMessagesDetailRouteImport } from './routes/_authed/_admin/messages/detail'
import { Route as AuthedAdminGroupsDetailRouteImport } from './routes/_authed/_admin/groups/detail'
import { Route as AuthedAdminEventsDetailRouteImport } from './routes/_authed/_admin/events/detail'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoleBasedAccessRoute = DocsRoleBasedAccessRouteImport.update({
  id: '/docs/role-based-access',
  path: '/docs/role-based-access',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsNotificationsRoute = DocsNotificationsRouteImport.update({
  id: '/docs/notifications',
  path: '/docs/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLicensingRoute = DocsLicensingRouteImport.update({
  id: '/docs/licensing',
  path: '/docs/licensing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGroupManagementRoute = DocsGroupManagementRouteImport.update({
  id: '/docs/group-management',
  path: '/docs/group-management',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsEventManagementRoute = DocsEventManagementRouteImport.update({
  id: '/docs/event-management',
  path: '/docs/event-management',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDeliveryTrackingRoute = DocsDeliveryTrackingRouteImport.update({
  id: '/docs/delivery-tracking',
  path: '/docs/delivery-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsBroadcastMessagesRoute = DocsBroadcastMessagesRouteImport.update({
  id: '/docs/broadcast-messages',
  path: '/docs/broadcast-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInboxRoute = AuthedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedMessagesIdRoute = AuthedMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminSystemSettingsRoute =
  AuthedAdminSystemSettingsRouteImport.update({
    id: '/system-settings',
    path: '/system-settings',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminDashboardRoute = AuthedAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminUsersIndexRoute = AuthedAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminMessagesIndexRoute =
  AuthedAdminMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminGroupsIndexRoute = AuthedAdminGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminEventsIndexRoute = AuthedAdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminMessagesNewRoute = AuthedAdminMessagesNewRouteImport.update({
  id: '/messages/new',
  path: '/messages/new',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminMessagesDetailRoute =
  AuthedAdminMessagesDetailRouteImport.update({
    id: '/messages/detail',
    path: '/messages/detail',
    getParentRoute: () => AuthedAdminRoute,
  } as any)
const AuthedAdminGroupsDetailRoute = AuthedAdminGroupsDetailRouteImport.update({
  id: '/groups/detail',
  path: '/groups/detail',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminEventsDetailRoute = AuthedAdminEventsDetailRouteImport.update({
  id: '/events/detail',
  path: '/events/detail',
  getParentRoute: () => AuthedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/launch': typeof LaunchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/inbox': typeof AuthedInboxRoute
  '/settings': typeof AuthedSettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/docs/broadcast-messages': typeof DocsBroadcastMessagesRoute
  '/docs/delivery-tracking': typeof DocsDeliveryTrackingRoute
  '/docs/event-management': typeof DocsEventManagementRoute
  '/docs/group-management': typeof DocsGroupManagementRoute
  '/docs/licensing': typeof DocsLicensingRoute
  '/docs/notifications': typeof DocsNotificationsRoute
  '/docs/role-based-access': typeof DocsRoleBasedAccessRoute
  '/articles/': typeof ArticlesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/dashboard': typeof AuthedAdminDashboardRoute
  '/system-settings': typeof AuthedAdminSystemSettingsRoute
  '/messages/$id': typeof AuthedMessagesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/detail': typeof AuthedAdminEventsDetailRoute
  '/groups/detail': typeof AuthedAdminGroupsDetailRoute
  '/messages/detail': typeof AuthedAdminMessagesDetailRoute
  '/messages/new': typeof AuthedAdminMessagesNewRoute
  '/events/': typeof AuthedAdminEventsIndexRoute
  '/groups/': typeof AuthedAdminGroupsIndexRoute
  '/messages/': typeof AuthedAdminMessagesIndexRoute
  '/users/': typeof AuthedAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/launch': typeof LaunchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/inbox': typeof AuthedInboxRoute
  '/settings': typeof AuthedSettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/docs/broadcast-messages': typeof DocsBroadcastMessagesRoute
  '/docs/delivery-tracking': typeof DocsDeliveryTrackingRoute
  '/docs/event-management': typeof DocsEventManagementRoute
  '/docs/group-management': typeof DocsGroupManagementRoute
  '/docs/licensing': typeof DocsLicensingRoute
  '/docs/notifications': typeof DocsNotificationsRoute
  '/docs/role-based-access': typeof DocsRoleBasedAccessRoute
  '/articles': typeof ArticlesIndexRoute
  '/docs': typeof DocsIndexRoute
  '/dashboard': typeof AuthedAdminDashboardRoute
  '/system-settings': typeof AuthedAdminSystemSettingsRoute
  '/messages/$id': typeof AuthedMessagesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/detail': typeof AuthedAdminEventsDetailRoute
  '/groups/detail': typeof AuthedAdminGroupsDetailRoute
  '/messages/detail': typeof AuthedAdminMessagesDetailRoute
  '/messages/new': typeof AuthedAdminMessagesNewRoute
  '/events': typeof AuthedAdminEventsIndexRoute
  '/groups': typeof AuthedAdminGroupsIndexRoute
  '/messages': typeof AuthedAdminMessagesIndexRoute
  '/users': typeof AuthedAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/launch': typeof LaunchRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/_admin': typeof AuthedAdminRouteWithChildren
  '/_authed/inbox': typeof AuthedInboxRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/docs/broadcast-messages': typeof DocsBroadcastMessagesRoute
  '/docs/delivery-tracking': typeof DocsDeliveryTrackingRoute
  '/docs/event-management': typeof DocsEventManagementRoute
  '/docs/group-management': typeof DocsGroupManagementRoute
  '/docs/licensing': typeof DocsLicensingRoute
  '/docs/notifications': typeof DocsNotificationsRoute
  '/docs/role-based-access': typeof DocsRoleBasedAccessRoute
  '/articles/': typeof ArticlesIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/_authed/_admin/dashboard': typeof AuthedAdminDashboardRoute
  '/_authed/_admin/system-settings': typeof AuthedAdminSystemSettingsRoute
  '/_authed/messages/$id': typeof AuthedMessagesIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/_admin/events/detail': typeof AuthedAdminEventsDetailRoute
  '/_authed/_admin/groups/detail': typeof AuthedAdminGroupsDetailRoute
  '/_authed/_admin/messages/detail': typeof AuthedAdminMessagesDetailRoute
  '/_authed/_admin/messages/new': typeof AuthedAdminMessagesNewRoute
  '/_authed/_admin/events/': typeof AuthedAdminEventsIndexRoute
  '/_authed/_admin/groups/': typeof AuthedAdminGroupsIndexRoute
  '/_authed/_admin/messages/': typeof AuthedAdminMessagesIndexRoute
  '/_authed/_admin/users/': typeof AuthedAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/launch'
    | '/sign-in'
    | '/sign-up'
    | '/inbox'
    | '/settings'
    | '/articles/$slug'
    | '/docs/broadcast-messages'
    | '/docs/delivery-tracking'
    | '/docs/event-management'
    | '/docs/group-management'
    | '/docs/licensing'
    | '/docs/notifications'
    | '/docs/role-based-access'
    | '/articles/'
    | '/docs/'
    | '/dashboard'
    | '/system-settings'
    | '/messages/$id'
    | '/api/auth/$'
    | '/events/detail'
    | '/groups/detail'
    | '/messages/detail'
    | '/messages/new'
    | '/events/'
    | '/groups/'
    | '/messages/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/launch'
    | '/sign-in'
    | '/sign-up'
    | '/inbox'
    | '/settings'
    | '/articles/$slug'
    | '/docs/broadcast-messages'
    | '/docs/delivery-tracking'
    | '/docs/event-management'
    | '/docs/group-management'
    | '/docs/licensing'
    | '/docs/notifications'
    | '/docs/role-based-access'
    | '/articles'
    | '/docs'
    | '/dashboard'
    | '/system-settings'
    | '/messages/$id'
    | '/api/auth/$'
    | '/events/detail'
    | '/groups/detail'
    | '/messages/detail'
    | '/messages/new'
    | '/events'
    | '/groups'
    | '/messages'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/launch'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/_admin'
    | '/_authed/inbox'
    | '/_authed/settings'
    | '/articles/$slug'
    | '/docs/broadcast-messages'
    | '/docs/delivery-tracking'
    | '/docs/event-management'
    | '/docs/group-management'
    | '/docs/licensing'
    | '/docs/notifications'
    | '/docs/role-based-access'
    | '/articles/'
    | '/docs/'
    | '/_authed/_admin/dashboard'
    | '/_authed/_admin/system-settings'
    | '/_authed/messages/$id'
    | '/api/auth/$'
    | '/_authed/_admin/events/detail'
    | '/_authed/_admin/groups/detail'
    | '/_authed/_admin/messages/detail'
    | '/_authed/_admin/messages/new'
    | '/_authed/_admin/events/'
    | '/_authed/_admin/groups/'
    | '/_authed/_admin/messages/'
    | '/_authed/_admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LaunchRoute: typeof LaunchRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  DocsBroadcastMessagesRoute: typeof DocsBroadcastMessagesRoute
  DocsDeliveryTrackingRoute: typeof DocsDeliveryTrackingRoute
  DocsEventManagementRoute: typeof DocsEventManagementRoute
  DocsGroupManagementRoute: typeof DocsGroupManagementRoute
  DocsLicensingRoute: typeof DocsLicensingRoute
  DocsNotificationsRoute: typeof DocsNotificationsRoute
  DocsRoleBasedAccessRoute: typeof DocsRoleBasedAccessRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/role-based-access': {
      id: '/docs/role-based-access'
      path: '/docs/role-based-access'
      fullPath: '/docs/role-based-access'
      preLoaderRoute: typeof DocsRoleBasedAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/notifications': {
      id: '/docs/notifications'
      path: '/docs/notifications'
      fullPath: '/docs/notifications'
      preLoaderRoute: typeof DocsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/licensing': {
      id: '/docs/licensing'
      path: '/docs/licensing'
      fullPath: '/docs/licensing'
      preLoaderRoute: typeof DocsLicensingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/group-management': {
      id: '/docs/group-management'
      path: '/docs/group-management'
      fullPath: '/docs/group-management'
      preLoaderRoute: typeof DocsGroupManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/event-management': {
      id: '/docs/event-management'
      path: '/docs/event-management'
      fullPath: '/docs/event-management'
      preLoaderRoute: typeof DocsEventManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/delivery-tracking': {
      id: '/docs/delivery-tracking'
      path: '/docs/delivery-tracking'
      fullPath: '/docs/delivery-tracking'
      preLoaderRoute: typeof DocsDeliveryTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/broadcast-messages': {
      id: '/docs/broadcast-messages'
      path: '/docs/broadcast-messages'
      fullPath: '/docs/broadcast-messages'
      preLoaderRoute: typeof DocsBroadcastMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inbox': {
      id: '/_authed/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthedInboxRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin': {
      id: '/_authed/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/messages/$id': {
      id: '/_authed/messages/$id'
      path: '/messages/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthedMessagesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_admin/system-settings': {
      id: '/_authed/_admin/system-settings'
      path: '/system-settings'
      fullPath: '/system-settings'
      preLoaderRoute: typeof AuthedAdminSystemSettingsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/dashboard': {
      id: '/_authed/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedAdminDashboardRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/users/': {
      id: '/_authed/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthedAdminUsersIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/messages/': {
      id: '/_authed/_admin/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthedAdminMessagesIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/groups/': {
      id: '/_authed/_admin/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthedAdminGroupsIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/events/': {
      id: '/_authed/_admin/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthedAdminEventsIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/messages/new': {
      id: '/_authed/_admin/messages/new'
      path: '/messages/new'
      fullPath: '/messages/new'
      preLoaderRoute: typeof AuthedAdminMessagesNewRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/messages/detail': {
      id: '/_authed/_admin/messages/detail'
      path: '/messages/detail'
      fullPath: '/messages/detail'
      preLoaderRoute: typeof AuthedAdminMessagesDetailRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/groups/detail': {
      id: '/_authed/_admin/groups/detail'
      path: '/groups/detail'
      fullPath: '/groups/detail'
      preLoaderRoute: typeof AuthedAdminGroupsDetailRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/_admin/events/detail': {
      id: '/_authed/_admin/events/detail'
      path: '/events/detail'
      fullPath: '/events/detail'
      preLoaderRoute: typeof AuthedAdminEventsDetailRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminDashboardRoute: typeof AuthedAdminDashboardRoute
  AuthedAdminSystemSettingsRoute: typeof AuthedAdminSystemSettingsRoute
  AuthedAdminEventsDetailRoute: typeof AuthedAdminEventsDetailRoute
  AuthedAdminGroupsDetailRoute: typeof AuthedAdminGroupsDetailRoute
  AuthedAdminMessagesDetailRoute: typeof AuthedAdminMessagesDetailRoute
  AuthedAdminMessagesNewRoute: typeof AuthedAdminMessagesNewRoute
  AuthedAdminEventsIndexRoute: typeof AuthedAdminEventsIndexRoute
  AuthedAdminGroupsIndexRoute: typeof AuthedAdminGroupsIndexRoute
  AuthedAdminMessagesIndexRoute: typeof AuthedAdminMessagesIndexRoute
  AuthedAdminUsersIndexRoute: typeof AuthedAdminUsersIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminDashboardRoute: AuthedAdminDashboardRoute,
  AuthedAdminSystemSettingsRoute: AuthedAdminSystemSettingsRoute,
  AuthedAdminEventsDetailRoute: AuthedAdminEventsDetailRoute,
  AuthedAdminGroupsDetailRoute: AuthedAdminGroupsDetailRoute,
  AuthedAdminMessagesDetailRoute: AuthedAdminMessagesDetailRoute,
  AuthedAdminMessagesNewRoute: AuthedAdminMessagesNewRoute,
  AuthedAdminEventsIndexRoute: AuthedAdminEventsIndexRoute,
  AuthedAdminGroupsIndexRoute: AuthedAdminGroupsIndexRoute,
  AuthedAdminMessagesIndexRoute: AuthedAdminMessagesIndexRoute,
  AuthedAdminUsersIndexRoute: AuthedAdminUsersIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedInboxRoute: typeof AuthedInboxRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedMessagesIdRoute: typeof AuthedMessagesIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedInboxRoute: AuthedInboxRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedMessagesIdRoute: AuthedMessagesIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LaunchRoute: LaunchRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  DocsBroadcastMessagesRoute: DocsBroadcastMessagesRoute,
  DocsDeliveryTrackingRoute: DocsDeliveryTrackingRoute,
  DocsEventManagementRoute: DocsEventManagementRoute,
  DocsGroupManagementRoute: DocsGroupManagementRoute,
  DocsLicensingRoute: DocsLicensingRoute,
  DocsNotificationsRoute: DocsNotificationsRoute,
  DocsRoleBasedAccessRoute: DocsRoleBasedAccessRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
